# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/rvelago/ZYBO_Z7/Bibliography/Arty-Z7-10-Master.xdc

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_processing_system7_0_1/design_1_processing_system7_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_1 || ORIG_REF_NAME==design_1_processing_system7_0_1} -quiet] -quiet

# XDC: c:/Users/rvelago/ZYBO_Z7/Projects/project_1_PS_Only_Bare_Metal/project_1_PS_Only_Bare_Metal.gen/sources_1/bd/design_1/design_1_ooc.xdc
